[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
lib_deps =https://github.com/ljk1331ljk/EVO-arduino.git

[env:OTA]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
upload_protocol = espota
upload_port = EvoX1-OTA.local
upload_flags = --host_port=55910, --auth=ArduinoOTAPassword
lib_deps =https://github.com/ljk1331ljk/EVO-arduino.git
